// <auto-generated />
namespace vendeglo_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class setMenuItemsNamemaxlenghtto200 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setMenuItemsNamemaxlenghtto200));
        
        string IMigrationMetadata.Id
        {
            get { return "201912021630424_set MenuItems.Name maxlenght to 200"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
