// <auto-generated />
namespace vendeglo_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class reversenavigationpropertyCategoryMenuItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reversenavigationpropertyCategoryMenuItems));
        
        string IMigrationMetadata.Id
        {
            get { return "202001081638325_reverse navigation property Category.MenuItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
